# Generated by Django 5.1.4 on 2025-12-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_livestream_video_conference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='livestream',
            new_name='livestream__course__4a7927_idx',
            old_name='livestream__course__6c2b47_idx',
        ),
        migrations.RenameIndex(
            model_name='livestream',
            new_name='livestream__instruc_a69504_idx',
            old_name='livestream__instruc_8d4e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='qaquestion',
            new_name='livestream__stream__e04460_idx',
            old_name='livestream__stream__4c8d1f_idx',
        ),
        migrations.RenameIndex(
            model_name='streamchat',
            new_name='livestream__stream__6f3e0b_idx',
            old_name='livestream__stream__9b2e5a_idx',
        ),
        migrations.RenameIndex(
            model_name='streamviewer',
            new_name='livestream__stream__975863_idx',
            old_name='livestream__stream__7a3c94_idx',
        ),
        migrations.RenameIndex(
            model_name='videoconference',
            new_name='livestream__course__0bd81a_idx',
            old_name='livestream__course__3f5a2e_idx',
        ),
        migrations.RenameIndex(
            model_name='videoconference',
            new_name='livestream__host_id_74adc1_idx',
            old_name='livestream__host_id_7e9b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='videoconference',
            new_name='livestream__status_ff21dc_idx',
            old_name='livestream__status_6d4c8f_idx',
        ),
        migrations.RenameIndex(
            model_name='videoconferenceparticipant',
            new_name='livestream__confere_6df0fd_idx',
            old_name='livestream__confere_2a5e9b_idx',
        ),
        migrations.RenameIndex(
            model_name='videoconferenceparticipant',
            new_name='livestream__user_id_b9db21_idx',
            old_name='livestream__user_id_1c4f7d_idx',
        ),
    ]
