# Generated by Django 5.1.4 on 2025-12-04 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Module title (e.g., 'Week 1: Introduction')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Module description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_published', models.BooleanField(default=True, help_text='Is this module visible to students?')),
                ('unlock_date', models.DateTimeField(blank=True, help_text='Optional date when module becomes available', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Material title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Material description')),
                ('material_type', models.CharField(choices=[('FILE', 'File'), ('VIDEO', 'Video'), ('LINK', 'External Link'), ('DOCUMENT', 'Document'), ('PRESENTATION', 'Presentation')], default='FILE', help_text='Type of material', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Uploaded file (PDF, video, document, etc.)', null=True, upload_to='course_materials/%Y/%m/')),
                ('url', models.URLField(blank=True, help_text='External URL (for links and videos)', max_length=500)),
                ('embed_code', models.TextField(blank=True, help_text='Embed code for videos (YouTube, Vimeo, etc.)')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within module')),
                ('is_required', models.BooleanField(default=False, help_text='Is this material required for course completion?')),
                ('is_downloadable', models.BooleanField(default=True, help_text='Allow students to download this material?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(help_text='Module this material belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.module')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='How long the student viewed the material (in seconds)', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Did the student complete viewing this material?')),
                ('material', models.ForeignKey(help_text='Material that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='courses.material')),
                ('student', models.ForeignKey(help_text='Student who viewed the material', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='material_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material View',
                'verbose_name_plural': 'Material Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['student', 'material'], name='courses_mat_student_1957bf_idx'), models.Index(fields=['material', '-viewed_at'], name='courses_mat_materia_159a91_idx')],
            },
        ),
    ]
