# Generated by Django 5.1.4 on 2025-12-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_module_material_materialview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_days',
            field=models.CharField(blank=True, help_text='Days of week (e.g., Mon, Wed, Fri)', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='class_time',
            field=models.TimeField(blank=True, help_text='Regular class meeting time (e.g., 10:00 AM)', null=True),
        ),
    ]
