# Generated by Django 5.1.4 on 2025-11-02 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('event_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment Due'), ('EXAM', 'Exam'), ('QUIZ', 'Quiz'), ('CLASS', 'Class Session'), ('OFFICE_HOURS', 'Office Hours'), ('REMINDER', 'Reminder'), ('OTHER', 'Other')], default='OTHER', help_text='Type of event', max_length=20)),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(blank=True, help_text='Event end date and time (optional)', null=True)),
                ('all_day', models.BooleanField(default=False, help_text='Is this an all-day event?')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for event display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Associated course (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.course')),
                ('created_by', models.ForeignKey(help_text='User who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date'],
            },
        ),
    ]
