# Generated by Django 5.1.4 on 2025-12-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiinteraction',
            new_name='ai_assistan_user_id_5fedf9_idx',
            old_name='ai_assistan_user_id_8b3f44_idx',
        ),
        migrations.RenameIndex(
            model_name='aiinteraction',
            new_name='ai_assistan_interac_8dd604_idx',
            old_name='ai_assistan_interac_7e5c91_idx',
        ),
    ]
