# Generated by Django 5.1.4 on 2025-12-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatnotification',
            new_name='chat_chatno_user_id_1a01de_idx',
            old_name='chat_chatn_user_id_2a4d6e_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_edc775_idx',
            old_name='chat_messag_room_id_ce4d6a_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_sender__62c9f9_idx',
            old_name='chat_messag_sender__0b5e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereadreceipt',
            new_name='chat_messag_user_id_eb7442_idx',
            old_name='chat_messa_user_id_8f3c42_idx',
        ),
        migrations.RenameIndex(
            model_name='userpresence',
            new_name='chat_userpr_room_id_4929a7_idx',
            old_name='chat_userpr_room_id_ac4178_idx',
        ),
    ]
