# Generated by Django 5.1.4 on 2025-10-30 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment title', max_length=200)),
                ('description', models.TextField(help_text='Assignment description and instructions')),
                ('assignment_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('QUIZ', 'Quiz'), ('PROJECT', 'Project'), ('EXAM', 'Exam'), ('ESSAY', 'Essay')], default='HOMEWORK', help_text='Type of assignment', max_length=20)),
                ('total_points', models.PositiveIntegerField(default=100, help_text='Maximum points for this assignment')),
                ('due_date', models.DateTimeField(help_text='Assignment due date')),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment (PDF, docs, etc.)', null=True, upload_to='assignment_files/')),
                ('allow_late_submission', models.BooleanField(default=False, help_text='Allow submissions after due date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, help_text='Text submission content')),
                ('attachment', models.FileField(blank=True, help_text='Submitted file', null=True, upload_to='submission_files/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded', models.BooleanField(default=False, help_text='Has been graded')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Points earned', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Instructor feedback')),
                ('graded_at', models.DateTimeField(blank=True, help_text='When submission was graded', null=True)),
                ('assignment', models.ForeignKey(help_text='Assignment being submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, help_text='Instructor who graded this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student making the submission', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
