# Generated by Django 5.1.4 on 2025-12-04 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('SHORT_ANSWER', 'Short Answer')], default='MULTIPLE_CHOICE', help_text='Type of question', max_length=20)),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering (optional)')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(help_text='Choice text or correct answer for short answer')),
                ('is_correct', models.BooleanField(default=False, help_text='Is this the correct answer?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for choices')),
                ('question', models.ForeignKey(help_text='Question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assignments.question')),
            ],
            options={
                'verbose_name': 'Question Choice',
                'verbose_name_plural': 'Question Choices',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (optional)', null=True)),
                ('allow_multiple_attempts', models.BooleanField(default=False, help_text='Allow students to retake the quiz')),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Show correct answers after submission')),
                ('randomize_questions', models.BooleanField(default=False, help_text='Randomize question order for each student')),
                ('pass_percentage', models.PositiveIntegerField(default=60, help_text='Percentage required to pass')),
                ('assignment', models.OneToOneField(help_text='Assignment this quiz is associated with', limit_choices_to={'assignment_type': 'QUIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='Quiz this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Which attempt number (1, 2, 3...)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Total points earned (auto-calculated)', null=True)),
                ('total_points', models.PositiveIntegerField(blank=True, help_text='Total possible points (auto-calculated)', null=True)),
                ('passed', models.BooleanField(default=False, help_text='Did student pass based on pass_percentage?')),
                ('quiz', models.ForeignKey(help_text='Quiz being attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assignments.quiz')),
                ('student', models.ForeignKey(help_text='Student taking the quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
                'unique_together': {('quiz', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text="Student's answer")),
                ('is_correct', models.BooleanField(blank=True, help_text='Is the answer correct? (set during grading)', null=True)),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points earned for this question')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(help_text='Quiz attempt this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assignments.quizattempt')),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assignments.question')),
            ],
            options={
                'verbose_name': 'Quiz Response',
                'verbose_name_plural': 'Quiz Responses',
                'ordering': ['question__order'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
